#!/bin/bash

./clean

# Get fields

echo  "Reading fields from parameters.xml..."

# CRLF in parameters.xml (Windows editor) puts \\r in argv and corrupts platform.xml.
if [ -f parameters.xml ]; then
	sed -i 's/\r$//' parameters.xml 2>/dev/null || true
fi

simulation_time=($(grep -oP '(?<=simulation_time>)[^<]+' parameters.xml | tr -d '\r'))
warm_up_time=($(grep -oP '(?<=warm_up_time>)[^<]+' parameters.xml | tr -d '\r'))

n_projects=($(grep -oP '(?<=n_projects>)[^<]+' parameters.xml | tr -d '\r'))
snumber=($(grep -oP '(?<=snumber>)[^<]+' parameters.xml | tr -d '\r'))
name=($(grep -oP '(?<=name>)[^<]+' parameters.xml | tr -d '\r'))
server_power=($(grep -oP '(?<=server_pw>)[^<]+' parameters.xml | tr -d '\r'))
disk_bw=($(grep -oP '(?<=disk_bw>)[^<]+' parameters.xml | tr -d '\r'))
ifgl_percentage=($(grep -oP '(?<=ifgl_percentage>)[^<]+' parameters.xml | tr -d '\r'))
ifcd_percentage=($(grep -oP '(?<=ifcd_percentage>)[^<]+' parameters.xml | tr -d '\r'))
input_file_size=($(grep -oP '(?<=input_file_size>)[^<]+' parameters.xml | tr -d '\r'))
averagewpif=($(grep -oP '(?<=averagewpif>)[^<]+' parameters.xml | tr -d '\r'))
task_fpops=($(grep -oP '(?<=task_fpops>)[^<]+' parameters.xml | tr -d '\r'))
delay_bound=($(grep -oP '(?<=delay_bound>)[^<]+' parameters.xml | tr -d '\r'))
output_file_size=($(grep -oP '(?<=output_file_size>)[^<]+' parameters.xml | tr -d '\r'))
min_quorum=($(grep -oP '(?<=min_quorum>)[^<]+' parameters.xml | tr -d '\r'))
target_nresults=($(grep -oP '(?<=target_nresults>)[^<]+' parameters.xml | tr -d '\r'))
max_error_results=($(grep -oP '(?<=max_error_results>)[^<]+' parameters.xml | tr -d '\r'))
max_total_results=($(grep -oP '(?<=max_total_results>)[^<]+' parameters.xml | tr -d '\r'))
success_percentage=($(grep -oP '(?<=success_percentage>)[^<]+' parameters.xml | tr -d '\r'))
canonical_percentage=($(grep -oP '(?<=canonical_percentage>)[^<]+' parameters.xml | tr -d '\r'))
max_success_results=($(grep -oP '(?<=max_success_results>)[^<]+' parameters.xml | tr -d '\r'))
output_file_storage=($(grep -oP '(?<=output_file_storage>)[^<]+' parameters.xml | tr -d '\r'))
dsreplication=($(grep -oP '(?<=dsreplication>)[^<]+' parameters.xml | tr -d '\r'))
dcreplication=($(grep -oP '(?<=dcreplication>)[^<]+' parameters.xml | tr -d '\r'))
nscheduling_servers=($(grep -oP '(?<=nscheduling_servers>)[^<]+' parameters.xml | tr -d '\r'))
ndata_servers=($(grep -oP '(?<=ndata_servers>)[^<]+' parameters.xml | tr -d '\r'))
ndata_client_servers=($(grep -oP '(?<=ndata_client_servers>)[^<]+' parameters.xml | tr -d '\r'))

n_groups=($(grep -oP '(?<=n_groups>)[^<]+' parameters.xml | tr -d '\r'))
n_clients=($(grep -oP '(?<=n_clients>)[^<]+' parameters.xml | tr -d '\r'))
ndata_clients=($(grep -oP '(?<=ndata_clients>)[^<]+' parameters.xml | tr -d '\r'))
connection_interval=($(grep -oP '(?<=connection_interval>)[^<]+' parameters.xml | tr -d '\r'))
scheduling_interval=($(grep -oP '(?<=scheduling_interval>)[^<]+' parameters.xml | tr -d '\r'))
gbw=($(grep -oP '(?<=gbw>)[^<]+' parameters.xml | tr -d '\r'))
glatency=($(grep -oP '(?<=glatency>)[^<]+' parameters.xml | tr -d '\r'))
traces_file=($(grep -oP '(?<=traces_file>)[^<]+' parameters.xml | tr -d '\r'))
max_speed=($(grep -oP '(?<=max_speed>)[^<]+' parameters.xml | tr -d '\r'))
min_speed=($(grep -oP '(?<=min_speed>)[^<]+' parameters.xml | tr -d '\r'))
pv_distri=($(grep -oP '(?<=pv_distri>)[^<]+' parameters.xml | tr -d '\r'))
pa_param=($(grep -oP '(?<=pa_param>)[^<]+' parameters.xml | tr -d '\r'))
pb_param=($(grep -oP '(?<=pb_param>)[^<]+' parameters.xml | tr -d '\r'))
db_distri=($(grep -oP '(?<=db_distri>)[^<]+' parameters.xml | tr -d '\r'))
da_param=($(grep -oP '(?<=da_param>)[^<]+' parameters.xml | tr -d '\r'))
db_param=($(grep -oP '(?<=db_param>)[^<]+' parameters.xml | tr -d '\r'))
av_distri=($(grep -oP '(?<=av_distri>)[^<]+' parameters.xml | tr -d '\r'))
aa_param=($(grep -oP '(?<=aa_param>)[^<]+' parameters.xml | tr -d '\r'))
ab_param=($(grep -oP '(?<=ab_param>)[^<]+' parameters.xml | tr -d '\r'))
nv_distri=($(grep -oP '(?<=nv_distri>)[^<]+' parameters.xml | tr -d '\r'))
na_param=($(grep -oP '(?<=na_param>)[^<]+' parameters.xml | tr -d '\r'))
nb_param=($(grep -oP '(?<=nb_param>)[^<]+' parameters.xml | tr -d '\r'))
dc_av_distri=($(grep -oP '(?<=dc_av_distri>)[^<]+' parameters.xml | tr -d '\r'))
dc_aa_param=($(grep -oP '(?<=dc_aa_param>)[^<]+' parameters.xml | tr -d '\r'))
dc_ab_param=($(grep -oP '(?<=dc_ab_param>)[^<]+' parameters.xml | tr -d '\r'))
dc_nv_distri=($(grep -oP '(?<=dc_nv_distri>)[^<]+' parameters.xml | tr -d '\r'))
dc_na_param=($(grep -oP '(?<=dc_na_param>)[^<]+' parameters.xml | tr -d '\r'))
dc_nb_param=($(grep -oP '(?<=dc_nb_param>)[^<]+' parameters.xml | tr -d '\r'))
att_projs=($(grep -oP '(?<=att_projs>)[^<]+' parameters.xml | tr -d '\r'))
pnumber=($(grep -oP '(?<=pnumber>)[^<]+' parameters.xml | tr -d '\r'))
priority=($(grep -oP '(?<=priority>)[^<]+' parameters.xml | tr -d '\r'))
lsbw=($(grep -oP '(?<=lsbw>)[^<]+' parameters.xml | tr -d '\r'))
lslatency=($(grep -oP '(?<=lslatency>)[^<]+' parameters.xml | tr -d '\r'))
ldbw=($(grep -oP '(?<=ldbw>)[^<]+' parameters.xml | tr -d '\r'))
ldlatency=($(grep -oP '(?<=ldlatency>)[^<]+' parameters.xml | tr -d '\r'))

echo "n_groups: $n_groups"
echo "Done"

let j=0
let total_clients=0
let total_data_clients=0;
let total_scheduling_servers=0
let total_data_servers=0
let total_data_client_servers=0

# Total data servers
for ((i=0; i<n_projects; i++))
do
	((total_data_servers+=${ndata_servers[$i]}))
	((total_scheduling_servers+=${nscheduling_servers[$i]}))
	((total_data_client_servers+=${ndata_client_servers[$i]}))
done 

# Total clients
for ((i=0; i<n_groups; i++))
do
	((total_clients+=${n_clients[$i]}))
	((total_data_clients+=${ndata_clients[$i]}))
done


# ksenia: next I also can take from the config file
# Compiling
echo -n "Compiling... "
cd build 
make > /dev/null
cd ..
echo "Done"

declare -a arg1	# Platform arguments
declare -a arg2	# Deployment arguments
declare -a arg3 # boinc_simulator args
declare -a arg4 # boinc_simulator args2

arg1[j++]=${n_groups}

# # BORRAR
# cd Traces/lhc/
# ./command_unsort
# cd ../..
# # FIN BORRAR

# Cluster arguments
for ((i=0; i<n_groups; i++))
do
	arg1[j++]=${glatency[$i]}
	arg1[j++]=${gbw[$i]}
	arg1[j++]=${n_clients[$i]}
done

arg1[j++]=${n_projects}

# Server arguments
for ((i=0; i<n_projects; i++))
do
	arg1[j++]=${server_power[$i]}
	arg1[j++]=${nscheduling_servers[$i]}
	arg1[j++]=${ndata_servers[$i]}
	arg1[j++]=${ndata_client_servers[$i]}
done

# Link arguments
for ((i=0, l=0; i<n_groups; i++))
do
  arg1[j++]=${att_projs[$i]}
  for((k=0; k<att_projs[i]; k++, l++))
  do
	arg1[j++]=${lslatency[$l]}
	arg1[j++]=${lsbw[$l]}
	arg1[j++]=${ldlatency[$l]}
	arg1[j++]=${ldbw[$l]}	
  done
done

# Route arguments
for ((i=0, l=0; i<n_groups; i++))
do
  for((k=0; k<att_projs[i]; k++, l++))
  do
	arg1[j++]=${pnumber[$l]}
  done
done

echo -n "Creating platform.xml... "
python3 python/xml2yaml.py

script_dir=$(dirname "$0")
script_dir=$(cd "$script_dir" && pwd)


##### Platform ######
cd build/Files
PROJECT_SOURCE_DIR="$script_dir" ./create_platform ${arg1[@]}

echo "Done"

let j=0

arg2[j++]=${n_projects}

# Server arguments
for ((i=0; i<n_projects; i++))
do
	arg2[j++]=${snumber[$i]}
	arg2[j++]=${name[$i]}
	arg2[j++]=${output_file_size[$i]}
	arg2[j++]=${task_fpops[$i]}
	arg2[j++]=${ifgl_percentage[$i]}
	arg2[j++]=${ifcd_percentage[$i]}
	arg2[j++]=${averagewpif[$i]}
	arg2[j++]=${min_quorum[$i]}
	arg2[j++]=${target_nresults[$i]}
	arg2[j++]=${max_error_results[$i]}
	arg2[j++]=${max_total_results[$i]}
	arg2[j++]=${max_success_results[$i]}
	arg2[j++]=${delay_bound[$i]}	
	arg2[j++]=${success_percentage[$i]}
	arg2[j++]=${canonical_percentage[$i]}		
	arg2[j++]=${input_file_size[$i]}
	arg2[j++]=${disk_bw[$i]}
	arg2[j++]=${ndata_servers[$i]}	
	arg2[j++]=${output_file_storage[$i]}
	arg2[j++]=${dsreplication[$i]}
	arg2[j++]=${dcreplication[$i]}
	arg2[j++]=${nscheduling_servers[$i]}		
	arg2[j++]=${ndata_client_servers[$i]}		
done

arg2[j++]=${n_groups}

# Client parameters
for ((i=0, l=0; i<n_groups; i++))
do
  arg2[j++]=${n_clients[$i]}
  arg2[j++]=${ndata_clients[$i]} 
  arg2[j++]=${att_projs[$i]}
  arg2[j++]=${traces_file[$i]}
  arg2[j++]=${connection_interval[$i]}
  arg2[j++]=${scheduling_interval[$i]}
  arg2[j++]=${max_speed[$i]}
  arg2[j++]=${min_speed[$i]}
  arg2[j++]=${pv_distri[$i]}
  arg2[j++]=${pa_param[$i]}
  arg2[j++]=${pb_param[$i]}
  arg2[j++]=${db_distri[$i]}
  arg2[j++]=${da_param[$i]}
  arg2[j++]=${db_param[$i]}
  arg2[j++]=${av_distri[$i]}
  arg2[j++]=${aa_param[$i]}
  arg2[j++]=${ab_param[$i]}
  arg2[j++]=${nv_distri[$i]}
  arg2[j++]=${na_param[$i]}
  arg2[j++]=${nb_param[$i]}
  arg2[j++]=${dc_av_distri[$i]}
  arg2[j++]=${dc_aa_param[$i]}
  arg2[j++]=${dc_ab_param[$i]}
  arg2[j++]=${dc_nv_distri[$i]}
  arg2[j++]=${dc_na_distri[$i]}
  arg2[j++]=${dc_nb_distri[$i]}
  for((k=0; k<att_projs[i]; k++, l++))
  do
	arg2[j++]=${pnumber[$l]}
	arg2[j++]=${priority[$l]}	
  done
done

##### Deployment ######

echo -n "Creating deployment.xml... "
PROJECT_SOURCE_DIR="$script_dir" ./create_deployment ../../parameters.yaml ${arg2[@]}
echo "Done"

cd ../..

# boinc_simulator arguments 
for ((i=0, k=0, l=0; i<n_groups; i++))
do
  for((j=0; j<att_projs[$i]; j++, k++))
  do
	((arg3[${pnumber[$k]}]+=${n_clients[$i]}))
  	((arg4[${pnumber[$k]}]+=${ndata_clients[$i]}))
  done
done

# //--cfg=contexts/stack_size:16
echo -n "Creating execute.sh... "
cat <<EOF >execute
#!/bin/bash

cd Files
LD_LIBRARY_PATH="/opt/boost/lib/" ../build/Files/boinc_sim_cpp platform.xml deployment.xml ../parameters.yaml
cd ..
EOF

chmod 0777 execute

echo "Done"

echo "Complete"
