simulation_time: 96
warm_up_time: 0
server_side:
    n_projects: 2
    sprojects:
      - snumber: 0
        name: RakeSearchtype1e15@home
        nscheduling_servers: 1
        ndata_servers: 1
        ndata_client_servers: 1
        server_pw: 12000000000f
        disk_bw: 167772160
        ifgl_percentage: 100
        ifcd_percentage: 100
        averagewpif: 1
        input_file_size: 1024
        task_fpops: 736000000000
        output_file_size: 11000
        min_quorum: 1
        target_nresults: 1
        max_error_results: 8
        max_total_results: 10
        max_success_results: 8
        delay_bound: 64800
        output_file_storage: 0
        dsreplication: 1
        dcreplication: 1
      - snumber: 1
        name: RakeSearchtype2e13@home
        nscheduling_servers: 1
        ndata_servers: 1
        ndata_client_servers: 1
        server_pw: 12000000000f
        disk_bw: 167772160
        ifgl_percentage: 100
        ifcd_percentage: 100
        averagewpif: 1
        input_file_size: 1024
        task_fpops: 736000000000
        output_file_size: 11000
        min_quorum: 1
        target_nresults: 1
        max_error_results: 8
        max_total_results: 10
        max_success_results: 8
        delay_bound: 64800
        output_file_storage: 0
        dsreplication: 1
        dcreplication: 1
client_side:
    n_groups: 2
    groups:
      - n_clients: 10
        ndata_clients: 1
        connection_interval: 60
        scheduling_interval: 3600
        gbw: 50Mbps
        glatency: 7.3ms
        traces_file: /Traces/boom_host_cpu
        max_speed: 800
        min_speed: 0.07
        pv_distri: 5
        pa_param: 0.0534
        pb_param: -1
        db_traces_file: /Traces/storage/boom_disk_capacity
        db_distri: 2
        da_param: 21.086878916910564
        db_param: 159.1597190181666
        av_distri: 1
        aa_param: 0.357
        ab_param: 43.652
        nv_distri: 8
        na_param: 0.338,0.390,0.272
        nb_param: 0.029,30.121,1.069
        att_projs: 2
        gprojects:
          - pnumber: 0
            priority: 10
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
            success_percentage: 98
            canonical_percentage: 84
          - pnumber: 1
            priority: 10
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
            success_percentage: 98
            canonical_percentage: 84
      - n_clients: 100
        ndata_clients: 1
        connection_interval: 60
        scheduling_interval: 3600
        gbw: 50Mbps
        glatency: 7.3ms
        traces_file: /Traces/boom_host_cpu
        max_speed: 800
        min_speed: 0.07
        pv_distri: 5
        pa_param: 0.0534
        pb_param: -1
        db_traces_file: /Traces/storage/boom_disk_capacity
        db_distri: 2
        da_param: 21.086878916910564
        db_param: 159.1597190181666
        av_distri: 1
        aa_param: 0.357
        ab_param: 43.652
        nv_distri: 8
        na_param: 0.338,0.390,0.272
        nb_param: 0.029,30.121,1.069
        att_projs: 2
        gprojects:
          - pnumber: 0
            priority: 10
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
            success_percentage: 98
            canonical_percentage: 84
          - pnumber: 1
            priority: 10
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
            success_percentage: 98
            canonical_percentage: 84
experiment_run:
    seed_for_deterministic_run:  6523446 
    measures:
        clean_before_write:  true 
        save_filepath:  /mnt/c/Users/rolan/Desktop/Projects/combos/python/configer/save_file.txt 
    timeline:
        execute_state_log_path:  /mnt/c/Users/rolan/Desktop/Projects/combos/exp/FLOPS_20_1500/execute_800_736000000000.csv 
        observable_clients:  c10,c11,c12,c13,c14,c15,c16,c20,c21,c22,c23,c24,c25,c26 
