#!/bin/bash

echo "Run '/generator'"

./generator

echo "Run '/execute'"

./execute

echo "Run analyzers"

export PYTHONPATH="$PYTHONPATH:/mnt/c/Users/rolan/Desktop/Projects/combos/python"
python3 python/main_analyzer.py
